LOAD DATA LOCAL INFILE 'C:/Users/lavanya/Documents/EXCELWORKS/DATA SETS/Real_Project_Dataset/fake_job_postings.csv'
INTO TABLE FAKE_JOB 
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SET GLOBAL LOCAL_INFILE=1;
SHOW GLOBAL VARIABLES LIKE 'LOCAL_INFILE';

SELECT * FROM FAKE_JOB;

CREATE TABLE JOB_ANALYSIS LIKE FAKE_JOB;
ALTER TABLE JOB_ANALYSIS ADD COLUMN ROW_NUM INT;
INSERT INTO JOB_ANALYSIS SELECT *,ROW_NUMBER() OVER( PARTITION BY 
  title, Country, State, City, department, salary_range, 
 telecommuting, has_company_logo, has_questions, employment_type, required_experience, required_education, industry, 
 `function`, fraudulent ) AS ROW_NUM FROM FAKE_JOB;
 
 SELECT * FROM JOB_ANALYSIS;

 
													    ###DATA CLEANING###
# 1.Remove Duplicate Value
SELECT * FROM JOB_ANALYSIS WHERE ROW_NUM>1;
#2. Standardize
ALTER TABLE JOB_ANALYSIS RENAME COLUMN ï»¿job_id TO job_id;
UPDATE FAKE_JOB SET TITLE=TRIM(TITLE);
UPDATE FAKE_JOB SET employment_type=TRIM(employment_type);

ALTER TABLE JOB_ANALYSIS ADD COLUMN salary_min INT ,  ADD COLUMN salary_max INT;
UPDATE JOB_ANALYSIS SET
SALARY_MIN = CAST(SUBSTR(SALARY_RANGE,1,LOCATE('-',SALARY_RANGE)-1) AS UNSIGNED),
SALARY_MAX = CAST(SUBSTR(SALARY_RANGE,LOCATE('-',SALARY_RANGE)+1) AS UNSIGNED) WHERE SALARY_RANGE IS NOT NULL  AND SALARY_RANGE !=''
AND LOCATE('-',SALARY_RANGE)>0;

UPDATE JOB_ANALYSIS SET SALARY_RANGE=NULL WHERE SALARY_RANGE='';
SELECT DISTINCT SALARY_RANGE FROM JOB_ANALYSIS  WHERE SALARY_RANGE IS NOT NULL AND SALARY_RANGE !='';
SELECT SALARY_MIN,SALARY_MAX FROM JOB_ANALYSIS   WHERE SALARY_RANGE IS NOT NULL AND SALARY_RANGE !='';

ALTER TABLE JOB_ANALYSIS DROP COLUMN SALARY_RANGE ;

SELECT 
  COALESCE(SUM(CASE WHEN title = '' THEN 1 END), 0) AS null_title,
  COALESCE(SUM(CASE WHEN Country = '' THEN 1 END), 0) AS null_country,
  COALESCE(SUM(CASE WHEN State = '' THEN 1 END), 0) AS null_state,
  COALESCE(SUM(CASE WHEN City = '' THEN 1 END), 0) AS null_city,
  COALESCE(SUM(CASE WHEN department = '' THEN 1 END), 0) AS null_dept,
  COALESCE(SUM(CASE WHEN employment_type = '' THEN 1 END), 0) AS null_emp,
  COALESCE(SUM(CASE WHEN required_experience = '' THEN 1 END), 0) AS null_exp,
  COALESCE(SUM(CASE WHEN required_education = '' THEN 1 END), 0) AS null_edu,
  COALESCE(SUM(CASE WHEN industry = '' THEN 1 END), 0) AS null_industry,
  COALESCE(SUM(CASE WHEN `function` = '' THEN 1 END), 0) AS null_function
FROM JOB_ANALYSIS;


SELECT 
  SUM(CASE WHEN title = '' THEN 1 END) AS empty_title,
  SUM(CASE WHEN Country = '' THEN 1 END) AS empty_country,
  SUM(CASE WHEN State = '' THEN 1 END) AS empty_state,
  SUM(CASE WHEN City = '' THEN 1 END) AS empty_city,
  SUM(CASE WHEN department = '' THEN 1 END) AS empty_dept,
  SUM(CASE WHEN employment_type = '' THEN 1 END) AS empty_emp,
  SUM(CASE WHEN required_experience = '' THEN 1 END) AS empty_exp,
  SUM(CASE WHEN required_education = '' THEN 1 END) AS empty_edu,
  SUM(CASE WHEN industry = '' THEN 1 END) AS empty_industry,
  SUM(CASE WHEN `function` = '' THEN 1 END) AS empty_function
FROM JOB_ANALYSIS;

UPDATE JOB_ANALYSIS SET  `function`='Unknown' WHERE `function` ='';

ALTER TABLE JOB_ANALYSIS DROP COLUMN ROW_NUM;
 
													#### CLEANED ####

# Q1.PERCENTAGE OF FRAUD
SELECT FRAUDULENT,COUNT(*)AS TOTAL,(COUNT(*)*100.0)/(SELECT COUNT(*) FROM JOB_ANALYSIS) AS PERCENTAGE
 FROM JOB_ANALYSIS GROUP BY FRAUDULENT ;
 SELECT DISTINCT FRAUDULENT FROM JOB_ANALYSIS;
 
SELECT COUNT(*) FROM JOB_ANALYSIS WHERE FRAUDULENT IS NULL;
DELETE FROM JOB_ANALYSIS WHERE FRAUDULENT IS NULL;

#Q2.WHICH INDUSTRIES HAVE HIGHEST FRAUDULENT
SELECT INDUSTRY,COUNT(FRAUDULENT)  FROM JOB_ANALYSIS WHERE FRAUDULENT=1  GROUP BY INDUSTRY ORDER BY COUNT(FRAUDULENT) DESC LIMIT 5;

#Q3. DOES TELECOMMUTING HAS HIGH FRAUD THAN NON
 
 SELECT TELECOMMUTING,
SUM(CASE WHEN FRAUDULENT=1 THEN 1 ELSE 0 END) AS FRAUD,
COUNT(*)AS TOTAL,
SUM((CASE WHEN FRAUDULENT=1 THEN 1 ELSE 0 END)*100.0)/COUNT(*) AS FRATE,
(COUNT(*)*100.0)/(SELECT COUNT(*) FROM JOB_ANALYSIS) AS PERCENTAGE
 FROM JOB_ANALYSIS GROUP BY TELECOMMUTING  ;

# Q5.LOCATION WITH MOST FRAUD
SELECT COUNTRY,STATE,CITY,COUNT(*) AS FRAUD FROM JOB_ANALYSIS
WHERE FRAUDULENT=1 GROUP BY COUNTRY,STATE,CITY ORDER BY COUNT(*) DESC LIMIT 10;
 
 #Q5. FRAUD JOB MENTION SALARY LESS OFTEN
 SELECT FRAUDULENT,
SUM(CASE WHEN SALARY_MIN IS NULL THEN 1 ELSE 0 END) AS FRAUD,
COUNT(*)AS TOTAL,
SUM((CASE WHEN SALARY_MIN IS NULL THEN 1 ELSE 0 END)*100.0)/COUNT(*) AS FRATE,
(COUNT(*)*100.0)/(SELECT COUNT(*) FROM JOB_ANALYSIS) AS NO_SAL
 FROM JOB_ANALYSIS GROUP BY FRAUDULENT  ;
 
 #Q6. EMPLOYEMENT_TYPE
 SELECT EMPLOYMENT_TYPE,
SUM(CASE WHEN FRAUDULENT=1 THEN 1 ELSE 0 END) AS FRAUD,
COUNT(*)AS TOTAL,
SUM((CASE WHEN FRAUDULENT=1 THEN 1 ELSE 0 END)*100.0)/COUNT(*) AS FRATE,
(COUNT(*)*100.0)/(SELECT COUNT(*) FROM JOB_ANALYSIS) AS NO_SAL
 FROM JOB_ANALYSIS GROUP BY EMPLOYMENT_TYPE  ;
 

